### ISSUE TITLE
一个资源释放的问题

### ISSUE THREAD

**Issue by myseemylife** [myhhub/ctkExample#1]
![image](https://user-images.githubusercontent.com/3964397/168075475-36058338-450b-4782-8602-70bfb596de8a.png)
请问这个new出来的窗口是在哪里释放的?

**Comment by myhhub** [comment]
没有释放，本文已经废除，新版本是[《CTK完整教程(OSGI for C++ 实现 C++ Qt 模块化)》](https://github.com/myhhub/CTK-project)。
